apiVersion: v1
kind: Service
metadata:
  name: studentdemo-service
  labels:
    app: studentdemo
spec:
  ports:
    - port: 80
  selector:
     app: studentdemo
     tier: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentdemo-deployment
  labels:
    app: studentdemo
spec:
  selector:
    matchLabels:
      app: studentdemo
      tier: api
  template:
    metadata:
      labels:
        app: studentdemo
        tier: api
    spec:
      containers:
      - image: demoforcr.azurecr.io/studentdemo
        resources:
            limits:
              memory: 512Mi
              cpu: "1"
        name: studentdemo
        env:
        - name: DB_HOST
          value: postgres-db-sertvice
        - name: DB_PASSWORD
          value: testpassword
        ports:
        - containerPort: 80
          name: studentdemo
