on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: liuyuchentit.azurecr.io
        username: ${{ secrets.acr_liuyuchentit_username }}
        password: ${{ secrets.acr_liuyuchentit_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/StudentDemo" -f  "StudentDemo/Dockerfile" -t liuyuchentit.azurecr.io/democluster:${{ github.sha }} --label dockerfile-path=StudentDemo/Dockerfile
        docker push liuyuchentit.azurecr.io/democluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_democluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: liuyuchentit.azurecr.io
        container-registry-username: ${{ secrets.acr_liuyuchentit_username }}
        container-registry-password: ${{ secrets.acr_liuyuchentit_password }}
        secret-name: democlusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          liuyuchentit.azurecr.io/democluster:${{ github.sha }}
        imagepullsecrets: |
          democlusterdockerauth
